apiVersion: v1
kind: Service
metadata:
  name: besu-node-2
  namespace: besu
  labels:
    app: besu-node-2
spec:
  selector:
    app: besu-node-2
  ports:
    - name: p2p
      port: 30303
      targetPort: 30303
    - name: rpc-http
      port: 8545
      targetPort: 8545
    - name: metrics
      port: 9545
      targetPort: 9545
