apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fabric
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://github.com/samerhijazi/shalm
    targetRevision: HEAD
    path: 02_gitops/fabric
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: fabric
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
