apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://github.com/samerhijazi/shalm
    targetRevision: HEAD
    path: 02_gitops/quarkus-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: quarkus-ui
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
