apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-ui
  namespace: quarkus-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-ui
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: quarkus-ui
    spec:
      containers:
        - name: quarkus-ui
          image: ghcr.io/samerhijazi/quarkus-ui:77f00d8a0a2fc2371e055026bb1e955d46c2c53e
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_LOG_CONSOLE_JSON
              value: "true"
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
