apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-ui
  namespace: quarkus-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-ui
  template:
    metadata:
      labels:
        app: quarkus-ui
    spec:
      containers:
        - name: quarkus-ui
          image: ghcr.io/samerhijazi/quarkus-ui:338e745b6687ef48d86e55f131980ff912a713c0
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_LOG_CONSOLE_JSON
              value: "true"
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
