apiVersion: v1
kind: Service
metadata:
  name: quarkus-ui
  namespace: quarkus-ui
  labels:
    app: quarkus-ui
spec:
  type: NodePort
  selector:
    app: quarkus-ui
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30801
