- name: Remove old containerd config (if exists)
  file:
    path: /etc/containerd/config.toml
    state: absent

- name: Install containerd
  apt:
    name: containerd
    state: present
    update_cache: yes

- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Generate default containerd config
  shell: containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml

- name: Enable systemd cgroup
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'
  when: ansible_check_mode == false

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes
