apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: quarkus-api
---
apiVersion: v1
kind: Namespace
metadata:
  name: quarkus-ui
---
apiVersion: v1
kind: Namespace
metadata:
  name: fabric
---
apiVersion: v1
kind: Namespace
metadata:
  name: besu
---
apiVersion: v1
kind: Namespace
metadata:
  name: identity
---
apiVersion: v1
kind: Namespace
metadata:
  name: ai
