apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: observability
spec:
  type: NodePort
  selector:
    app: jaeger
  ports:
    - name: ui
      port: 16686
      targetPort: 16686
      nodePort: 30686
    - name: zipkin
      port: 9411
      targetPort: 9411
    - name: collector
      port: 14268
      targetPort: 14268
