all:
  children:
    k8s:
      children:
        master:
          hosts:
            k8s-master:
              ansible_host: 192.168.105.3
              ansible_user: ubuntu

        workers:
          hosts:
            k8s-worker-01:
              ansible_host: 192.168.105.4
              ansible_user: ubuntu

            k8s-worker-02:
              ansible_host: 192.168.105.5
              ansible_user: ubuntu
