apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: peer0-org1-data
  namespace: fabric
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
