quarkus.application.name=quarkus-ui
quarkus.http.port=8080

# REST client — points to quarkus-api K8s service
quarkus.rest-client.api.url=http://quarkus-api.quarkus-api.svc.cluster.local:8080

# JSON logging
quarkus.log.console.json=true

# Health
quarkus.smallrye-health.root-path=/health
