apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: fabric-permissive
  namespace: fabric
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  mtls:
    mode: PERMISSIVE
