apiVersion: v1
kind: Service
metadata:
  name: peer0-org2
  namespace: fabric
spec:
  selector:
    app: peer0-org2
  ports:
    - name: grpc
      port: 7051
      targetPort: 7051
    - name: chaincode
      port: 7052
      targetPort: 7052
