OrdererOrgs:
  - Name: Orderer
    Domain: shalm.local
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.shalm.local
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Org2
    Domain: org2.shalm.local
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
